name: CI - PHP + HTML + JS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Descargar código
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configurar PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    # Instalar dependencias si existen
    - name: Install dependencies
      run: |
        if [ -f composer.json ]; then
          composer install --no-interaction --prefer-dist
        else
          echo "No hay composer.json, se omite instalación"
        fi

    # Revisar sintaxis PHP
    - name: PHP Lint
      run: find . -name "*.php" -exec php -l {} \;
