name: Probar conexión Supabase

on:
  push:
    branches:
      - main

jobs:
  test-php:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Probar conexión a Supabase
        run: |
          echo "<?php
          require_once __DIR__ . '/conexion.php';
          \$conexion = new ConexionSupabase();
          \$resultado = \$conexion->request('GET', '/tu_tabla?limit=1');
          if (isset(\$resultado['error'])) {
              echo 'Error en la conexión: ' . \$resultado['error'];
          } else {
              echo 'Conexión exitosa a Supabase: ';
              print_r(\$resultado);
          }
          ?>" > test.php

          php test.php

          sudo apt-get update
          sudo apt-get install -y php-curl php-xml php-mbstring

      - name: Probar conexión Supabase
        run: php test_supabase.php
