name: Probar conexión Supabase

on:
  push:
    branches:
      - main

jobs:
  test-php:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar extensiones PHP necesarias
        run: |
          sudo apt-get update
          sudo apt-get install -y php-curl php-xml php-mbstring

      - name: Ejecutar prueba de conexión Supabase
        run: |
          php -r "
          require_once __DIR__ . '/bd/conexion.php';
          \$conn = new ConexionSupabase();
          \$response = \$conn->request('GET', '/');
          if (isset(\$response['error'])) {
              echo 'Error al conectar con Supabase\n';
              var_dump(\$response);
              exit(1);
          } else {
              echo 'Conexión exitosa con Supabase\n';
          }
          "
